### ISSUE TITLE
Does not support method ```each_row_streaming```

### ISSUE THREAD

**Issue by bramski** [roo-rb/roo-xls#14]
This is a method that base Roo::Base supports, but this gem does not.

**Comment by distroid** [comment]
how fix it?

**Comment by sektorcap** [comment]
+1

**Comment by caiotkt** [comment]
+1

**Comment by tgturner** [comment]
Unfortunately it will not be possible to suppourt this for XLS. XLS is a binary format and we rely on the `spreadsheet` gem to interpret it. Nokogiri, which we rely on for `roo` allows us to stream XLSX content as XLSX are XML files.
