### ISSUE TITLE
Switch to read_xls gem - MIT

### ISSUE THREAD

**Issue by jetaggart** [roo-rb/roo-xls#19]
I've finished the first pass at an xls parser. It works for our needs for now, but is missing a lot of the functionality of `spreadsheet` for sure. Do you have an idea of what the minimum feature set it'd need to support to replace `spreadsheet`?

We also don't have a good sample size of excel spreadsheets to feel comfortable that it fully parses all xls docs. Does anyone have some decent spreadsheets to write tests against to get more coverage?

The gem is here: https://github.com/p2bi/read_xls

**Comment by stevendaniels** [comment]
Awesome work. I like the API. I don't know if you can specify a minimum feature set, but you should definitely decide what parts of the spec you plan to support for what version of the gem. 

Did any of the spreadsheets in this repo's `test/files` directory help?

**Comment by jetaggart** [comment]
They would definitely help. I'll add most (all?) of those to our test suite. Just wanted to gauge interest before moving forward. 

I think we need to support a `sheet.cell(1, "A")` style API at a minimum; it'd probably be good after that.

**Comment by stevendaniels** [comment]
I'll take a look at what would be needed to swap read_xls in to roo-xls.
