### ISSUE TITLE
Roo-xls reads xls file but nil object returned

### ISSUE THREAD

**Issue by varunagrawal** [roo-rb/roo-xls#25]
``` ruby
spreadsheet = open_spreadsheet(file)

# This line prints out "Sheet0" which is the correct sheet name
puts spreadsheet.default_sheet

# Prints nil
puts spreadsheet 

# Throws an error that `upto` is not defined on nilClass
# I assume the code fails because of this line 
# https://github.com/roo-rb/roo/blob/master/lib/roo/base.rb#L197
headers = spreadsheet.row(1)
```

I am using Rails 4.0.13 with Ruby 2.1.0

**Comment by varunagrawal** [comment]
Any updates on this?

**Comment by tgturner** [comment]
@varunagrawal can you provide an example spreadsheet?

**Comment by varunagrawal** [comment]
I am no longer working on that project so I don't have access to the exact spreadsheet to reproduce the bug. I believe we figured out that the server was returning a malformed spreadsheet somehow which Excel was able to fix, but roo-xls was having a hard time with. 
I will close this issue since I don't know what can be done about it.

**Comment by brilnius** [comment]
For anyone landing on this issue like me...
I had the same problem, the XLSX file had two tabs, the first one being empty. After removing the first empty tab there was no more error.
