### ISSUE TITLE
roo-xls still using deprecated roo method make_tempdir

### ISSUE THREAD

**Issue by nnc** [roo-rb/roo-xls#28]
This results in this message being printed:

`[DEPRECATION] extend Roo::Tempdir and use its .make_tempdir instead`

This method is used [here](https://github.com/roo-rb/roo-xls/blob/master/lib/roo/xls/excel.rb#L30) and [here](https://github.com/roo-rb/roo-xls/blob/master/lib/roo/xls/excel_2003_xml.rb#L12).

**Comment by janklimo** [comment]
I believe this has been resolved by https://github.com/roo-rb/roo-xls/pull/37 and available in `v1.1.0`

**Comment by nnc** [comment]
Thanks @janklimo. It looks like it has been resolved.

**Comment by janklimo** [comment]
@Empact can you guys please push the latest version to RubyGems.org? `1.1.0` is only available from Github at the moment.

**Comment by Empact** [comment]
Unfortunately the [roo-xls gem](https://rubygems.org/gems/roo-xls) was first published by @simonoff, so only he can give me permissions to publish, and I've sent a few emails without response. Trying his other address now...

**Comment by simonoff** [comment]
Hello all! I'm really sorry! On rubygems my old email and I has issues with my Apple Mail rules so I never seen emails from github :(

**Comment by janklimo** [comment]
I can see `1.1.0` on RubyGems.org now. Thank you @simonoff!
