### ISSUE TITLE
roo-xls : merged cells should *all* return a value

### ISSUE THREAD

**Issue by haritak** [roo-rb/roo-xls#30]
Currently only the first of the merged cells is returning a value.
The rest cells are nil.

Example:
Suppose cells A1, A2, A3 are merged with value "ROO IS GREAT".
Reading of A1 returns the value. A2 and A3 return nil.

Related: https://github.com/roo-rb/roo/pull/171 [according to roo changelog, this has been implemented]

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

*** LOCAL GEMS ***
roo (2.5.1, 2.4.0)
roo-xls (1.0.0)

best regards,
Charitakis Yannis

**Comment by ms-ati** [comment]
Noticed the same thing. In pull request #45, added something to the README explaining that this option isn't currently supported in Roo::Xls. This seems better than nothing.
