### ISSUE TITLE
Text cells are returned as numbers

### ISSUE THREAD

**Issue by paneq** [roo-rb/roo-xls#46]
When I generate a file with a column containing ISBN numbers and format this columns/cells to be of type "text", after reading with roo-xls, the data comes as Float instead of String.

```
{:isbn=>9781609731939.0, :quantity=>10.0}
```

![screenshot 2018-05-22 10 32 29](https://user-images.githubusercontent.com/65587/40350926-7237c228-5dab-11e8-9adf-e67ffa14291a.png)

**Comment by tgturner** [comment]
@paneq Unfortunately, according to this thread https://github.com/zdavatz/spreadsheet/issues/41#issuecomment-132725639 there is not currently a way to do this properly with XLS files. I would recommend using XLSX if possible, or forcing the data to a string if you know its suppose to be a string.
