### ISSUE TITLE
read fields as text

### ISSUE THREAD

**Issue by lluis** [roo-rb/roo-xls#5]
like in roo-rb/roo#139 I need to read values from an xls as strings

on issuecomment-49214362 there's a way to do it:

```
cell = s.cell(row,col)
cell = s.excelx_value(row,col) if s.excelx_type(row,col) == [:numeric_or_formula, "General"]
```

can I do the same in roo-xls?

thanks!

**Comment by stevendaniels** [comment]
No. :cry:
